name: persikota
description: "Persikota adalah sebuah aplikasi yang dirancang untuk memenuhi tugas mata kuliah pengembangan aplikasi mobile. Aplikasi ini tidak memiliki tujuan komersial atau penggunaan praktis di dunia nyata, melainkan hanya sebagai proyek pura-pura yang dibuat untuk menunjukkan pemahaman dan keterampilan dalam pengembangan aplikasi."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  dio: ^5.4.0
  hive: ^2.2.3
  path_provider: ^2.0.11
  google_sign_in: ^6.2.1
  cloud_firestore: ^5.0.1
  intl: ^0.19.0
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
  fonts:
    - family: PoetsenOne
      fonts:
        - asset: assets/fonts/PoetsenOne-Regular.ttf
