// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwawAbqHvTf_3q91-sWnKldkjypUBx6HA',
    appId: '1:808199342468:web:58eea7656eea3068c535d1',
    messagingSenderId: '808199342468',
    projectId: 'persikota-a380d',
    authDomain: 'persikota-a380d.firebaseapp.com',
    storageBucket: 'persikota-a380d.appspot.com',
    measurementId: 'G-VVLHXM01K1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4QfFekBQvex9uhXMFOseK-8HMKjTSlFs',
    appId: '1:808199342468:android:b5f5c1b49a1192b9c535d1',
    messagingSenderId: '808199342468',
    projectId: 'persikota-a380d',
    storageBucket: 'persikota-a380d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0inHB76vM-gOFp8Qfh5PPfNDWR3DpXxQ',
    appId: '1:808199342468:ios:8edc2823180931eec535d1',
    messagingSenderId: '808199342468',
    projectId: 'persikota-a380d',
    storageBucket: 'persikota-a380d.appspot.com',
    androidClientId: '808199342468-0s2jnhun34jdfr66mpj1af538f1oct1j.apps.googleusercontent.com',
    iosClientId: '808199342468-bao53ho3c46giorbg332erg2gil146pn.apps.googleusercontent.com',
    iosBundleId: 'com.example.persikota',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0inHB76vM-gOFp8Qfh5PPfNDWR3DpXxQ',
    appId: '1:808199342468:ios:8edc2823180931eec535d1',
    messagingSenderId: '808199342468',
    projectId: 'persikota-a380d',
    storageBucket: 'persikota-a380d.appspot.com',
    androidClientId: '808199342468-0s2jnhun34jdfr66mpj1af538f1oct1j.apps.googleusercontent.com',
    iosClientId: '808199342468-bao53ho3c46giorbg332erg2gil146pn.apps.googleusercontent.com',
    iosBundleId: 'com.example.persikota',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwawAbqHvTf_3q91-sWnKldkjypUBx6HA',
    appId: '1:808199342468:web:a0479a415a99d188c535d1',
    messagingSenderId: '808199342468',
    projectId: 'persikota-a380d',
    authDomain: 'persikota-a380d.firebaseapp.com',
    storageBucket: 'persikota-a380d.appspot.com',
    measurementId: 'G-M2KZ1V0JFJ',
  );

}